// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/common/BaseButton.vue')['default']
    BaseHeading: typeof import('./components/common/BaseHeading.vue')['default']
    BaseInput: typeof import('./components/common/BaseInput.vue')['default']
    BaseLabel: typeof import('./components/common/BaseLabel.vue')['default']
    BaseLink: typeof import('./components/common/BaseLink.vue')['default']
    BaseNotification: typeof import('./components/common/BaseNotification.vue')['default']
    BaseTextarea: typeof import('./components/common/BaseTextarea.vue')['default']
  }
}

export { }
